test: &default

  # Credentials for REST APIs
  client_id: AaBGAI_ZJo2h-qrHBe3jHBvB_b0b7w5MtXYQfgAcwDuj_NaxThFBAcMI44J6eMp6T1D6BrbSnH1znEmP
  client_secret: ENoq5fmhJV651NktnjbMadAEeVe7y3hLThwbhB0OlBHKceURGpuwlGySaA8yg3rtLx4RkczkrFqt1hLN

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  <<: *default
  mode: live
  client_id: <%= ENV["PAYPAL_CLIENT_ID"] %>
  client_secret: <%= ENV["PAYPAL_CLIENT_SECRET"] %>
