# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fb8446e0bb910e20659546fb39b134825badfed086090399269d9a8a268f2088778ca9fd92baf8a9fd30155549fd67dc650fd726689cdcdd5550ef694b91e70

test:
  secret_key_base: 4d069a114bcef09f3c7a3b1b6adacca76195477becaeb73144d116bd23efbb1e9603b8e88e8f4a2610a50fe6f41e460e70c95904d8770b3c546c8edc0e020ece

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
